export enum BINS_LEGAL_TYPE {
  PHYSICAL = 'PHYSICAL',
  CORPORATE = 'CORPORATE',
  INSTALLMENT = 'INSTALLMENT',
  RETIREMENT = 'RETIREMENT',
  UNDEFINED = 'UNDEFINED'
}

export enum BINS_PROCESSING_TYPES {
  UZCARD = 'UZCARD',
  TIETO = 'TIETO',
  HUMO = 'HUMO'
}

export enum BINS_CARD_TYPES {
  HUMO = 'HUMO',
  UZCARD = 'UZCARD',
  VISA = 'VISA',
  MASTERCARD = 'MASTERCARD'
}
